creg -x ../newData/trainXall/AGN.json -y ../newData/trainYall/AGN.txt --l1 1 --z ../newData/weightAll/AGN.txt 2> /dev/null
creg -x ../newData/trainXall/EOG.json -y ../newData/trainYall/EOG.txt --l1 1 --z ../newData/weightAll/EOG.txt 2> /dev/null
creg -x ../newData/trainXall/WLP.json -y ../newData/trainYall/WLP.txt --l1 1 --z ../newData/weightAll/WLP.txt 2> /dev/null
creg -x ../newData/trainXall/CPB.json -y ../newData/trainYall/CPB.txt --l1 1 --z ../newData/weightAll/CPB.txt 2> /dev/null
creg -x ../newData/trainXall/YUM.json -y ../newData/trainYall/YUM.txt --l1 1 --z ../newData/weightAll/YUM.txt 2> /dev/null
creg -x ../newData/trainXall/JWN.json -y ../newData/trainYall/JWN.txt --l1 1 --z ../newData/weightAll/JWN.txt 2> /dev/null
creg -x ../newData/trainXall/TAP.json -y ../newData/trainYall/TAP.txt --l1 1 --z ../newData/weightAll/TAP.txt 2> /dev/null
creg -x ../newData/trainXall/WM.json -y ../newData/trainYall/WM.txt --l1 1 --z ../newData/weightAll/WM.txt 2> /dev/null
creg -x ../newData/trainXall/SPG.json -y ../newData/trainYall/SPG.txt --l1 1 --z ../newData/weightAll/SPG.txt 2> /dev/null
creg -x ../newData/trainXall/FIS.json -y ../newData/trainYall/FIS.txt --l1 1 --z ../newData/weightAll/FIS.txt 2> /dev/null
creg -x ../newData/trainXall/GT.json -y ../newData/trainYall/GT.txt --l1 1 --z ../newData/weightAll/GT.txt 2> /dev/null
creg -x ../newData/trainXall/GIS.json -y ../newData/trainYall/GIS.txt --l1 1 --z ../newData/weightAll/GIS.txt 2> /dev/null
creg -x ../newData/trainXall/MJN.json -y ../newData/trainYall/MJN.txt --l1 1 --z ../newData/weightAll/MJN.txt 2> /dev/null
creg -x ../newData/trainXall/ROP.json -y ../newData/trainYall/ROP.txt --l1 1 --z ../newData/weightAll/ROP.txt 2> /dev/null
creg -x ../newData/trainXall/GE.json -y ../newData/trainYall/GE.txt --l1 1 --z ../newData/weightAll/GE.txt 2> /dev/null
creg -x ../newData/trainXall/GD.json -y ../newData/trainYall/GD.txt --l1 1 --z ../newData/weightAll/GD.txt 2> /dev/null
creg -x ../newData/trainXall/VAR.json -y ../newData/trainYall/VAR.txt --l1 1 --z ../newData/weightAll/VAR.txt 2> /dev/null
creg -x ../newData/trainXall/AMZN.json -y ../newData/trainYall/AMZN.txt --l1 1 --z ../newData/weightAll/AMZN.txt 2> /dev/null
creg -x ../newData/trainXall/MAS.json -y ../newData/trainYall/MAS.txt --l1 1 --z ../newData/weightAll/MAS.txt 2> /dev/null
creg -x ../newData/trainXall/MAR.json -y ../newData/trainYall/MAR.txt --l1 1 --z ../newData/weightAll/MAR.txt 2> /dev/null
creg -x ../newData/trainXall/MAT.json -y ../newData/trainYall/MAT.txt --l1 1 --z ../newData/weightAll/MAT.txt 2> /dev/null
creg -x ../newData/trainXall/SNA.json -y ../newData/trainYall/SNA.txt --l1 1 --z ../newData/weightAll/SNA.txt 2> /dev/null
creg -x ../newData/trainXall/SNI.json -y ../newData/trainYall/SNI.txt --l1 1 --z ../newData/weightAll/SNI.txt 2> /dev/null
creg -x ../newData/trainXall/XRAY.json -y ../newData/trainYall/XRAY.txt --l1 1 --z ../newData/weightAll/XRAY.txt 2> /dev/null
creg -x ../newData/trainXall/JNJ.json -y ../newData/trainYall/JNJ.txt --l1 1 --z ../newData/weightAll/JNJ.txt 2> /dev/null
creg -x ../newData/trainXall/TSN.json -y ../newData/trainYall/TSN.txt --l1 1 --z ../newData/weightAll/TSN.txt 2> /dev/null
creg -x ../newData/trainXall/TSO.json -y ../newData/trainYall/TSO.txt --l1 1 --z ../newData/weightAll/TSO.txt 2> /dev/null
creg -x ../newData/trainXall/BEN.json -y ../newData/trainYall/BEN.txt --l1 1 --z ../newData/weightAll/BEN.txt 2> /dev/null
creg -x ../newData/trainXall/CMI.json -y ../newData/trainYall/CMI.txt --l1 1 --z ../newData/weightAll/CMI.txt 2> /dev/null
creg -x ../newData/trainXall/DISCA.json -y ../newData/trainYall/DISCA.txt --l1 1 --z ../newData/weightAll/DISCA.txt 2> /dev/null
creg -x ../newData/trainXall/CMG.json -y ../newData/trainYall/CMG.txt --l1 1 --z ../newData/weightAll/CMG.txt 2> /dev/null
creg -x ../newData/trainXall/CME.json -y ../newData/trainYall/CME.txt --l1 1 --z ../newData/weightAll/CME.txt 2> /dev/null
creg -x ../newData/trainXall/DTE.json -y ../newData/trainYall/DTE.txt --l1 1 --z ../newData/weightAll/DTE.txt 2> /dev/null
creg -x ../newData/trainXall/PCL.json -y ../newData/trainYall/PCL.txt --l1 1 --z ../newData/weightAll/PCL.txt 2> /dev/null
creg -x ../newData/trainXall/CMS.json -y ../newData/trainYall/CMS.txt --l1 1 --z ../newData/weightAll/CMS.txt 2> /dev/null
creg -x ../newData/trainXall/DTV.json -y ../newData/trainYall/DTV.txt --l1 1 --z ../newData/weightAll/DTV.txt 2> /dev/null
creg -x ../newData/trainXall/VLO.json -y ../newData/trainYall/VLO.txt --l1 1 --z ../newData/weightAll/VLO.txt 2> /dev/null
creg -x ../newData/trainXall/HUM.json -y ../newData/trainYall/HUM.txt --l1 1 --z ../newData/weightAll/HUM.txt 2> /dev/null
creg -x ../newData/trainXall/APOL.json -y ../newData/trainYall/APOL.txt --l1 1 --z ../newData/weightAll/APOL.txt 2> /dev/null
creg -x ../newData/trainXall/PCLN.json -y ../newData/trainYall/PCLN.txt --l1 1 --z ../newData/weightAll/PCLN.txt 2> /dev/null
creg -x ../newData/trainXall/FSLR.json -y ../newData/trainYall/FSLR.txt --l1 1 --z ../newData/weightAll/FSLR.txt 2> /dev/null
creg -x ../newData/trainXall/HCP.json -y ../newData/trainYall/HCP.txt --l1 1 --z ../newData/weightAll/HCP.txt 2> /dev/null
creg -x ../newData/trainXall/IGT.json -y ../newData/trainYall/IGT.txt --l1 1 --z ../newData/weightAll/IGT.txt 2> /dev/null
creg -x ../newData/trainXall/K.json -y ../newData/trainYall/K.txt --l1 1 --z ../newData/weightAll/K.txt 2> /dev/null
creg -x ../newData/trainXall/FFIV.json -y ../newData/trainYall/FFIV.txt --l1 1 --z ../newData/weightAll/FFIV.txt 2> /dev/null
creg -x ../newData/trainXall/BLL.json -y ../newData/trainYall/BLL.txt --l1 1 --z ../newData/weightAll/BLL.txt 2> /dev/null
creg -x ../newData/trainXall/ORLY.json -y ../newData/trainYall/ORLY.txt --l1 1 --z ../newData/weightAll/ORLY.txt 2> /dev/null
creg -x ../newData/trainXall/BLK.json -y ../newData/trainYall/BLK.txt --l1 1 --z ../newData/weightAll/BLK.txt 2> /dev/null
creg -x ../newData/trainXall/FTI.json -y ../newData/trainYall/FTI.txt --l1 1 --z ../newData/weightAll/FTI.txt 2> /dev/null
creg -x ../newData/trainXall/HCN.json -y ../newData/trainYall/HCN.txt --l1 1 --z ../newData/weightAll/HCN.txt 2> /dev/null
creg -x ../newData/trainXall/NFX.json -y ../newData/trainYall/NFX.txt --l1 1 --z ../newData/weightAll/NFX.txt 2> /dev/null
creg -x ../newData/trainXall/MA.json -y ../newData/trainYall/MA.txt --l1 1 --z ../newData/weightAll/MA.txt 2> /dev/null
creg -x ../newData/trainXall/CBG.json -y ../newData/trainYall/CBG.txt --l1 1 --z ../newData/weightAll/CBG.txt 2> /dev/null
creg -x ../newData/trainXall/PRGO.json -y ../newData/trainYall/PRGO.txt --l1 1 --z ../newData/weightAll/PRGO.txt 2> /dev/null
creg -x ../newData/trainXall/MO.json -y ../newData/trainYall/MO.txt --l1 1 --z ../newData/weightAll/MO.txt 2> /dev/null
creg -x ../newData/trainXall/NOC.json -y ../newData/trainYall/NOC.txt --l1 1 --z ../newData/weightAll/NOC.txt 2> /dev/null
creg -x ../newData/trainXall/MU.json -y ../newData/trainYall/MU.txt --l1 1 --z ../newData/weightAll/MU.txt 2> /dev/null
creg -x ../newData/trainXall/CBS.json -y ../newData/trainYall/CBS.txt --l1 1 --z ../newData/weightAll/CBS.txt 2> /dev/null
creg -x ../newData/trainXall/NDAQ.json -y ../newData/trainYall/NDAQ.txt --l1 1 --z ../newData/weightAll/NDAQ.txt 2> /dev/null
creg -x ../newData/trainXall/SE.json -y ../newData/trainYall/SE.txt --l1 1 --z ../newData/weightAll/SE.txt 2> /dev/null
creg -x ../newData/trainXall/MS.json -y ../newData/trainYall/MS.txt --l1 1 --z ../newData/weightAll/MS.txt 2> /dev/null
creg -x ../newData/trainXall/TJX.json -y ../newData/trainYall/TJX.txt --l1 1 --z ../newData/weightAll/TJX.txt 2> /dev/null
creg -x ../newData/trainXall/NOV.json -y ../newData/trainYall/NOV.txt --l1 1 --z ../newData/weightAll/NOV.txt 2> /dev/null
creg -x ../newData/trainXall/AMGN.json -y ../newData/trainYall/AMGN.txt --l1 1 --z ../newData/weightAll/AMGN.txt 2> /dev/null
creg -x ../newData/trainXall/COST.json -y ../newData/trainYall/COST.txt --l1 1 --z ../newData/weightAll/COST.txt 2> /dev/null
creg -x ../newData/trainXall/FE.json -y ../newData/trainYall/FE.txt --l1 1 --z ../newData/weightAll/FE.txt 2> /dev/null
creg -x ../newData/trainXall/CTL.json -y ../newData/trainYall/CTL.txt --l1 1 --z ../newData/weightAll/CTL.txt 2> /dev/null
creg -x ../newData/trainXall/ADBE.json -y ../newData/trainYall/ADBE.txt --l1 1 --z ../newData/weightAll/ADBE.txt 2> /dev/null
creg -x ../newData/trainXall/DOV.json -y ../newData/trainYall/DOV.txt --l1 1 --z ../newData/weightAll/DOV.txt 2> /dev/null
creg -x ../newData/trainXall/DOW.json -y ../newData/trainYall/DOW.txt --l1 1 --z ../newData/weightAll/DOW.txt 2> /dev/null
creg -x ../newData/trainXall/MSFT.json -y ../newData/trainYall/MSFT.txt --l1 1 --z ../newData/weightAll/MSFT.txt 2> /dev/null
creg -x ../newData/trainXall/GLW.json -y ../newData/trainYall/GLW.txt --l1 1 --z ../newData/weightAll/GLW.txt 2> /dev/null
creg -x ../newData/trainXall/SCHW.json -y ../newData/trainYall/SCHW.txt --l1 1 --z ../newData/weightAll/SCHW.txt 2> /dev/null
creg -x ../newData/trainXall/BSX.json -y ../newData/trainYall/BSX.txt --l1 1 --z ../newData/weightAll/BSX.txt 2> /dev/null
creg -x ../newData/trainXall/FCX.json -y ../newData/trainYall/FCX.txt --l1 1 --z ../newData/weightAll/FCX.txt 2> /dev/null
creg -x ../newData/trainXall/SPLS.json -y ../newData/trainYall/SPLS.txt --l1 1 --z ../newData/weightAll/SPLS.txt 2> /dev/null
creg -x ../newData/trainXall/UPS.json -y ../newData/trainYall/UPS.txt --l1 1 --z ../newData/weightAll/UPS.txt 2> /dev/null
creg -x ../newData/trainXall/WHR.json -y ../newData/trainYall/WHR.txt --l1 1 --z ../newData/weightAll/WHR.txt 2> /dev/null
creg -x ../newData/trainXall/BBBY.json -y ../newData/trainYall/BBBY.txt --l1 1 --z ../newData/weightAll/BBBY.txt 2> /dev/null
creg -x ../newData/trainXall/MDT.json -y ../newData/trainYall/MDT.txt --l1 1 --z ../newData/weightAll/MDT.txt 2> /dev/null
creg -x ../newData/trainXall/ZMH.json -y ../newData/trainYall/ZMH.txt --l1 1 --z ../newData/weightAll/ZMH.txt 2> /dev/null
creg -x ../newData/trainXall/F.json -y ../newData/trainYall/F.txt --l1 1 --z ../newData/weightAll/F.txt 2> /dev/null
creg -x ../newData/trainXall/DFS.json -y ../newData/trainYall/DFS.txt --l1 1 --z ../newData/weightAll/DFS.txt 2> /dev/null
creg -x ../newData/trainXall/JEC.json -y ../newData/trainYall/JEC.txt --l1 1 --z ../newData/weightAll/JEC.txt 2> /dev/null
creg -x ../newData/trainXall/V.json -y ../newData/trainYall/V.txt --l1 1 --z ../newData/weightAll/V.txt 2> /dev/null
creg -x ../newData/trainXall/FMC.json -y ../newData/trainYall/FMC.txt --l1 1 --z ../newData/weightAll/FMC.txt 2> /dev/null
creg -x ../newData/trainXall/ALL.json -y ../newData/trainYall/ALL.txt --l1 1 --z ../newData/weightAll/ALL.txt 2> /dev/null
creg -x ../newData/trainXall/NTAP.json -y ../newData/trainYall/NTAP.txt --l1 1 --z ../newData/weightAll/NTAP.txt 2> /dev/null
creg -x ../newData/trainXall/LMT.json -y ../newData/trainYall/LMT.txt --l1 1 --z ../newData/weightAll/LMT.txt 2> /dev/null
creg -x ../newData/trainXall/MMM.json -y ../newData/trainYall/MMM.txt --l1 1 --z ../newData/weightAll/MMM.txt 2> /dev/null
creg -x ../newData/trainXall/SO.json -y ../newData/trainYall/SO.txt --l1 1 --z ../newData/weightAll/SO.txt 2> /dev/null
creg -x ../newData/trainXall/JNPR.json -y ../newData/trainYall/JNPR.txt --l1 1 --z ../newData/weightAll/JNPR.txt 2> /dev/null
creg -x ../newData/trainXall/MMC.json -y ../newData/trainYall/MMC.txt --l1 1 --z ../newData/weightAll/MMC.txt 2> /dev/null
creg -x ../newData/trainXall/WEC.json -y ../newData/trainYall/WEC.txt --l1 1 --z ../newData/weightAll/WEC.txt 2> /dev/null
creg -x ../newData/trainXall/DPS.json -y ../newData/trainYall/DPS.txt --l1 1 --z ../newData/weightAll/DPS.txt 2> /dev/null
creg -x ../newData/trainXall/IBM.json -y ../newData/trainYall/IBM.txt --l1 1 --z ../newData/weightAll/IBM.txt 2> /dev/null
creg -x ../newData/trainXall/BAX.json -y ../newData/trainYall/BAX.txt --l1 1 --z ../newData/weightAll/BAX.txt 2> /dev/null
creg -x ../newData/trainXall/CAT.json -y ../newData/trainYall/CAT.txt --l1 1 --z ../newData/weightAll/CAT.txt 2> /dev/null
creg -x ../newData/trainXall/CAH.json -y ../newData/trainYall/CAH.txt --l1 1 --z ../newData/weightAll/CAH.txt 2> /dev/null
creg -x ../newData/trainXall/BAC.json -y ../newData/trainYall/BAC.txt --l1 1 --z ../newData/weightAll/BAC.txt 2> /dev/null
creg -x ../newData/trainXall/CAM.json -y ../newData/trainYall/CAM.txt --l1 1 --z ../newData/weightAll/CAM.txt 2> /dev/null
creg -x ../newData/trainXall/GS.json -y ../newData/trainYall/GS.txt --l1 1 --z ../newData/weightAll/GS.txt 2> /dev/null
creg -x ../newData/trainXall/CAG.json -y ../newData/trainYall/CAG.txt --l1 1 --z ../newData/weightAll/CAG.txt 2> /dev/null
creg -x ../newData/trainXall/LO.json -y ../newData/trainYall/LO.txt --l1 1 --z ../newData/weightAll/LO.txt 2> /dev/null
creg -x ../newData/trainXall/LM.json -y ../newData/trainYall/LM.txt --l1 1 --z ../newData/weightAll/LM.txt 2> /dev/null
creg -x ../newData/trainXall/LH.json -y ../newData/trainYall/LH.txt --l1 1 --z ../newData/weightAll/LH.txt 2> /dev/null
creg -x ../newData/trainXall/PGR.json -y ../newData/trainYall/PGR.txt --l1 1 --z ../newData/weightAll/PGR.txt 2> /dev/null
creg -x ../newData/trainXall/HIG.json -y ../newData/trainYall/HIG.txt --l1 1 --z ../newData/weightAll/HIG.txt 2> /dev/null
creg -x ../newData/trainXall/CELG.json -y ../newData/trainYall/CELG.txt --l1 1 --z ../newData/weightAll/CELG.txt 2> /dev/null
creg -x ../newData/trainXall/A.json -y ../newData/trainYall/A.txt --l1 1 --z ../newData/weightAll/A.txt 2> /dev/null
creg -x ../newData/trainXall/ABC.json -y ../newData/trainYall/ABC.txt --l1 1 --z ../newData/weightAll/ABC.txt 2> /dev/null
creg -x ../newData/trainXall/ZION.json -y ../newData/trainYall/ZION.txt --l1 1 --z ../newData/weightAll/ZION.txt 2> /dev/null
creg -x ../newData/trainXall/STI.json -y ../newData/trainYall/STI.txt --l1 1 --z ../newData/weightAll/STI.txt 2> /dev/null
creg -x ../newData/trainXall/STJ.json -y ../newData/trainYall/STJ.txt --l1 1 --z ../newData/weightAll/STJ.txt 2> /dev/null
creg -x ../newData/trainXall/STT.json -y ../newData/trainYall/STT.txt --l1 1 --z ../newData/weightAll/STT.txt 2> /dev/null
creg -x ../newData/trainXall/ABT.json -y ../newData/trainYall/ABT.txt --l1 1 --z ../newData/weightAll/ABT.txt 2> /dev/null
creg -x ../newData/trainXall/XOM.json -y ../newData/trainYall/XOM.txt --l1 1 --z ../newData/weightAll/XOM.txt 2> /dev/null
creg -x ../newData/trainXall/STX.json -y ../newData/trainYall/STX.txt --l1 1 --z ../newData/weightAll/STX.txt 2> /dev/null
creg -x ../newData/trainXall/STZ.json -y ../newData/trainYall/STZ.txt --l1 1 --z ../newData/weightAll/STZ.txt 2> /dev/null
creg -x ../newData/trainXall/BHI.json -y ../newData/trainYall/BHI.txt --l1 1 --z ../newData/weightAll/BHI.txt 2> /dev/null
creg -x ../newData/trainXall/CERN.json -y ../newData/trainYall/CERN.txt --l1 1 --z ../newData/weightAll/CERN.txt 2> /dev/null
creg -x ../newData/trainXall/PNR.json -y ../newData/trainYall/PNR.txt --l1 1 --z ../newData/weightAll/PNR.txt 2> /dev/null
creg -x ../newData/trainXall/CMA.json -y ../newData/trainYall/CMA.txt --l1 1 --z ../newData/weightAll/CMA.txt 2> /dev/null
creg -x ../newData/trainXall/IVZ.json -y ../newData/trainYall/IVZ.txt --l1 1 --z ../newData/weightAll/IVZ.txt 2> /dev/null
creg -x ../newData/trainXall/PNC.json -y ../newData/trainYall/PNC.txt --l1 1 --z ../newData/weightAll/PNC.txt 2> /dev/null
creg -x ../newData/trainXall/BXP.json -y ../newData/trainYall/BXP.txt --l1 1 --z ../newData/weightAll/BXP.txt 2> /dev/null
creg -x ../newData/trainXall/VFC.json -y ../newData/trainYall/VFC.txt --l1 1 --z ../newData/weightAll/VFC.txt 2> /dev/null
creg -x ../newData/trainXall/XLNX.json -y ../newData/trainYall/XLNX.txt --l1 1 --z ../newData/weightAll/XLNX.txt 2> /dev/null
creg -x ../newData/trainXall/AON.json -y ../newData/trainYall/AON.txt --l1 1 --z ../newData/weightAll/AON.txt 2> /dev/null
creg -x ../newData/trainXall/RAI.json -y ../newData/trainYall/RAI.txt --l1 1 --z ../newData/weightAll/RAI.txt 2> /dev/null
creg -x ../newData/trainXall/PRU.json -y ../newData/trainYall/PRU.txt --l1 1 --z ../newData/weightAll/PRU.txt 2> /dev/null
creg -x ../newData/trainXall/RF.json -y ../newData/trainYall/RF.txt --l1 1 --z ../newData/weightAll/RF.txt 2> /dev/null
creg -x ../newData/trainXall/RL.json -y ../newData/trainYall/RL.txt --l1 1 --z ../newData/weightAll/RL.txt 2> /dev/null
creg -x ../newData/trainXall/URBN.json -y ../newData/trainYall/URBN.txt --l1 1 --z ../newData/weightAll/URBN.txt 2> /dev/null
creg -x ../newData/trainXall/CHK.json -y ../newData/trainYall/CHK.txt --l1 1 --z ../newData/weightAll/CHK.txt 2> /dev/null
creg -x ../newData/trainXall/L.json -y ../newData/trainYall/L.txt --l1 1 --z ../newData/weightAll/L.txt 2> /dev/null
creg -x ../newData/trainXall/HRS.json -y ../newData/trainYall/HRS.txt --l1 1 --z ../newData/weightAll/HRS.txt 2> /dev/null
creg -x ../newData/trainXall/HRL.json -y ../newData/trainYall/HRL.txt --l1 1 --z ../newData/weightAll/HRL.txt 2> /dev/null
creg -x ../newData/trainXall/MRO.json -y ../newData/trainYall/MRO.txt --l1 1 --z ../newData/weightAll/MRO.txt 2> /dev/null
creg -x ../newData/trainXall/MRK.json -y ../newData/trainYall/MRK.txt --l1 1 --z ../newData/weightAll/MRK.txt 2> /dev/null
creg -x ../newData/trainXall/HRB.json -y ../newData/trainYall/HRB.txt --l1 1 --z ../newData/weightAll/HRB.txt 2> /dev/null
creg -x ../newData/trainXall/IPG.json -y ../newData/trainYall/IPG.txt --l1 1 --z ../newData/weightAll/IPG.txt 2> /dev/null
creg -x ../newData/trainXall/RHT.json -y ../newData/trainYall/RHT.txt --l1 1 --z ../newData/weightAll/RHT.txt 2> /dev/null
creg -x ../newData/trainXall/TYC.json -y ../newData/trainYall/TYC.txt --l1 1 --z ../newData/weightAll/TYC.txt 2> /dev/null
creg -x ../newData/trainXall/RHI.json -y ../newData/trainYall/RHI.txt --l1 1 --z ../newData/weightAll/RHI.txt 2> /dev/null
creg -x ../newData/trainXall/APH.json -y ../newData/trainYall/APH.txt --l1 1 --z ../newData/weightAll/APH.txt 2> /dev/null
creg -x ../newData/trainXall/ROST.json -y ../newData/trainYall/ROST.txt --l1 1 --z ../newData/weightAll/ROST.txt 2> /dev/null
creg -x ../newData/trainXall/APC.json -y ../newData/trainYall/APC.txt --l1 1 --z ../newData/weightAll/APC.txt 2> /dev/null
creg -x ../newData/trainXall/APA.json -y ../newData/trainYall/APA.txt --l1 1 --z ../newData/weightAll/APA.txt 2> /dev/null
creg -x ../newData/trainXall/APD.json -y ../newData/trainYall/APD.txt --l1 1 --z ../newData/weightAll/APD.txt 2> /dev/null
creg -x ../newData/trainXall/KSS.json -y ../newData/trainYall/KSS.txt --l1 1 --z ../newData/weightAll/KSS.txt 2> /dev/null
creg -x ../newData/trainXall/WFM.json -y ../newData/trainYall/WFM.txt --l1 1 --z ../newData/weightAll/WFM.txt 2> /dev/null
creg -x ../newData/trainXall/WFC.json -y ../newData/trainYall/WFC.txt --l1 1 --z ../newData/weightAll/WFC.txt 2> /dev/null
creg -x ../newData/trainXall/IFF.json -y ../newData/trainYall/IFF.txt --l1 1 --z ../newData/weightAll/IFF.txt 2> /dev/null
creg -x ../newData/trainXall/NVDA.json -y ../newData/trainYall/NVDA.txt --l1 1 --z ../newData/weightAll/NVDA.txt 2> /dev/null
creg -x ../newData/trainXall/LUK.json -y ../newData/trainYall/LUK.txt --l1 1 --z ../newData/weightAll/LUK.txt 2> /dev/null
creg -x ../newData/trainXall/RTN.json -y ../newData/trainYall/RTN.txt --l1 1 --z ../newData/weightAll/RTN.txt 2> /dev/null
creg -x ../newData/trainXall/BMS.json -y ../newData/trainYall/BMS.txt --l1 1 --z ../newData/weightAll/BMS.txt 2> /dev/null
creg -x ../newData/trainXall/BMY.json -y ../newData/trainYall/BMY.txt --l1 1 --z ../newData/weightAll/BMY.txt 2> /dev/null
creg -x ../newData/trainXall/AFL.json -y ../newData/trainYall/AFL.txt --l1 1 --z ../newData/weightAll/AFL.txt 2> /dev/null
creg -x ../newData/trainXall/EL.json -y ../newData/trainYall/EL.txt --l1 1 --z ../newData/weightAll/EL.txt 2> /dev/null
creg -x ../newData/trainXall/PAYX.json -y ../newData/trainYall/PAYX.txt --l1 1 --z ../newData/weightAll/PAYX.txt 2> /dev/null
creg -x ../newData/trainXall/OXY.json -y ../newData/trainYall/OXY.txt --l1 1 --z ../newData/weightAll/OXY.txt 2> /dev/null
creg -x ../newData/trainXall/SHW.json -y ../newData/trainYall/SHW.txt --l1 1 --z ../newData/weightAll/SHW.txt 2> /dev/null
creg -x ../newData/trainXall/GCI.json -y ../newData/trainYall/GCI.txt --l1 1 --z ../newData/weightAll/GCI.txt 2> /dev/null
creg -x ../newData/trainXall/ED.json -y ../newData/trainYall/ED.txt --l1 1 --z ../newData/weightAll/ED.txt 2> /dev/null
creg -x ../newData/trainXall/EA.json -y ../newData/trainYall/EA.txt --l1 1 --z ../newData/weightAll/EA.txt 2> /dev/null
creg -x ../newData/trainXall/CSC.json -y ../newData/trainYall/CSC.txt --l1 1 --z ../newData/weightAll/CSC.txt 2> /dev/null
creg -x ../newData/trainXall/CSX.json -y ../newData/trainYall/CSX.txt --l1 1 --z ../newData/weightAll/CSX.txt 2> /dev/null
creg -x ../newData/trainXall/EW.json -y ../newData/trainYall/EW.txt --l1 1 --z ../newData/weightAll/EW.txt 2> /dev/null
creg -x ../newData/trainXall/BTU.json -y ../newData/trainYall/BTU.txt --l1 1 --z ../newData/weightAll/BTU.txt 2> /dev/null
creg -x ../newData/trainXall/LUV.json -y ../newData/trainYall/LUV.txt --l1 1 --z ../newData/weightAll/LUV.txt 2> /dev/null
creg -x ../newData/trainXall/MUR.json -y ../newData/trainYall/MUR.txt --l1 1 --z ../newData/weightAll/MUR.txt 2> /dev/null
creg -x ../newData/trainXall/ATI.json -y ../newData/trainYall/ATI.txt --l1 1 --z ../newData/weightAll/ATI.txt 2> /dev/null
creg -x ../newData/trainXall/WYN.json -y ../newData/trainYall/WYN.txt --l1 1 --z ../newData/weightAll/WYN.txt 2> /dev/null
creg -x ../newData/trainXall/JBL.json -y ../newData/trainYall/JBL.txt --l1 1 --z ../newData/weightAll/JBL.txt 2> /dev/null
creg -x ../newData/trainXall/ADSK.json -y ../newData/trainYall/ADSK.txt --l1 1 --z ../newData/weightAll/ADSK.txt 2> /dev/null
creg -x ../newData/trainXall/ECL.json -y ../newData/trainYall/ECL.txt --l1 1 --z ../newData/weightAll/ECL.txt 2> /dev/null
creg -x ../newData/trainXall/SNDK.json -y ../newData/trainYall/SNDK.txt --l1 1 --z ../newData/weightAll/SNDK.txt 2> /dev/null
creg -x ../newData/trainXall/SEE.json -y ../newData/trainYall/SEE.txt --l1 1 --z ../newData/weightAll/SEE.txt 2> /dev/null
creg -x ../newData/trainXall/DGX.json -y ../newData/trainYall/DGX.txt --l1 1 --z ../newData/weightAll/DGX.txt 2> /dev/null
creg -x ../newData/trainXall/NUE.json -y ../newData/trainYall/NUE.txt --l1 1 --z ../newData/weightAll/NUE.txt 2> /dev/null
creg -x ../newData/trainXall/PCP.json -y ../newData/trainYall/PCP.txt --l1 1 --z ../newData/weightAll/PCP.txt 2> /dev/null
creg -x ../newData/trainXall/EXPE.json -y ../newData/trainYall/EXPE.txt --l1 1 --z ../newData/weightAll/EXPE.txt 2> /dev/null
creg -x ../newData/trainXall/EXPD.json -y ../newData/trainYall/EXPD.txt --l1 1 --z ../newData/weightAll/EXPD.txt 2> /dev/null
creg -x ../newData/trainXall/UNP.json -y ../newData/trainYall/UNP.txt --l1 1 --z ../newData/weightAll/UNP.txt 2> /dev/null
creg -x ../newData/trainXall/ETFC.json -y ../newData/trainYall/ETFC.txt --l1 1 --z ../newData/weightAll/ETFC.txt 2> /dev/null
creg -x ../newData/trainXall/DUK.json -y ../newData/trainYall/DUK.txt --l1 1 --z ../newData/weightAll/DUK.txt 2> /dev/null
creg -x ../newData/trainXall/XL.json -y ../newData/trainYall/XL.txt --l1 1 --z ../newData/weightAll/XL.txt 2> /dev/null
creg -x ../newData/trainXall/CLF.json -y ../newData/trainYall/CLF.txt --l1 1 --z ../newData/weightAll/CLF.txt 2> /dev/null
creg -x ../newData/trainXall/R.json -y ../newData/trainYall/R.txt --l1 1 --z ../newData/weightAll/R.txt 2> /dev/null
creg -x ../newData/trainXall/CLX.json -y ../newData/trainYall/CLX.txt --l1 1 --z ../newData/weightAll/CLX.txt 2> /dev/null
creg -x ../newData/trainXall/FDO.json -y ../newData/trainYall/FDO.txt --l1 1 --z ../newData/weightAll/FDO.txt 2> /dev/null
creg -x ../newData/trainXall/BBY.json -y ../newData/trainYall/BBY.txt --l1 1 --z ../newData/weightAll/BBY.txt 2> /dev/null
creg -x ../newData/trainXall/UNH.json -y ../newData/trainYall/UNH.txt --l1 1 --z ../newData/weightAll/UNH.txt 2> /dev/null
creg -x ../newData/trainXall/BBT.json -y ../newData/trainYall/BBT.txt --l1 1 --z ../newData/weightAll/BBT.txt 2> /dev/null
creg -x ../newData/trainXall/UNM.json -y ../newData/trainYall/UNM.txt --l1 1 --z ../newData/weightAll/UNM.txt 2> /dev/null
creg -x ../newData/trainXall/OMC.json -y ../newData/trainYall/OMC.txt --l1 1 --z ../newData/weightAll/OMC.txt 2> /dev/null
creg -x ../newData/trainXall/KO.json -y ../newData/trainYall/KO.txt --l1 1 --z ../newData/weightAll/KO.txt 2> /dev/null
creg -x ../newData/trainXall/VMC.json -y ../newData/trainYall/VMC.txt --l1 1 --z ../newData/weightAll/VMC.txt 2> /dev/null
creg -x ../newData/trainXall/NU.json -y ../newData/trainYall/NU.txt --l1 1 --z ../newData/weightAll/NU.txt 2> /dev/null
creg -x ../newData/trainXall/KR.json -y ../newData/trainYall/KR.txt --l1 1 --z ../newData/weightAll/KR.txt 2> /dev/null
creg -x ../newData/trainXall/LNC.json -y ../newData/trainYall/LNC.txt --l1 1 --z ../newData/weightAll/LNC.txt 2> /dev/null
creg -x ../newData/trainXall/KEY.json -y ../newData/trainYall/KEY.txt --l1 1 --z ../newData/weightAll/KEY.txt 2> /dev/null
creg -x ../newData/trainXall/ITW.json -y ../newData/trainYall/ITW.txt --l1 1 --z ../newData/weightAll/ITW.txt 2> /dev/null
creg -x ../newData/trainXall/KLAC.json -y ../newData/trainYall/KLAC.txt --l1 1 --z ../newData/weightAll/KLAC.txt 2> /dev/null
creg -x ../newData/trainXall/DO.json -y ../newData/trainYall/DO.txt --l1 1 --z ../newData/weightAll/DO.txt 2> /dev/null
creg -x ../newData/trainXall/SWK.json -y ../newData/trainYall/SWK.txt --l1 1 --z ../newData/weightAll/SWK.txt 2> /dev/null
creg -x ../newData/trainXall/RSG.json -y ../newData/trainYall/RSG.txt --l1 1 --z ../newData/weightAll/RSG.txt 2> /dev/null
creg -x ../newData/trainXall/WYNN.json -y ../newData/trainYall/WYNN.txt --l1 1 --z ../newData/weightAll/WYNN.txt 2> /dev/null
creg -x ../newData/trainXall/SWN.json -y ../newData/trainYall/SWN.txt --l1 1 --z ../newData/weightAll/SWN.txt 2> /dev/null
creg -x ../newData/trainXall/DF.json -y ../newData/trainYall/DF.txt --l1 1 --z ../newData/weightAll/DF.txt 2> /dev/null
creg -x ../newData/trainXall/DD.json -y ../newData/trainYall/DD.txt --l1 1 --z ../newData/weightAll/DD.txt 2> /dev/null
creg -x ../newData/trainXall/DE.json -y ../newData/trainYall/DE.txt --l1 1 --z ../newData/weightAll/DE.txt 2> /dev/null
creg -x ../newData/trainXall/SWY.json -y ../newData/trainYall/SWY.txt --l1 1 --z ../newData/weightAll/SWY.txt 2> /dev/null
creg -x ../newData/trainXall/PNW.json -y ../newData/trainYall/PNW.txt --l1 1 --z ../newData/weightAll/PNW.txt 2> /dev/null
creg -x ../newData/trainXall/TGT.json -y ../newData/trainYall/TGT.txt --l1 1 --z ../newData/weightAll/TGT.txt 2> /dev/null
creg -x ../newData/trainXall/HBAN.json -y ../newData/trainYall/HBAN.txt --l1 1 --z ../newData/weightAll/HBAN.txt 2> /dev/null
creg -x ../newData/trainXall/BIG.json -y ../newData/trainYall/BIG.txt --l1 1 --z ../newData/weightAll/BIG.txt 2> /dev/null
creg -x ../newData/trainXall/BIIB.json -y ../newData/trainYall/BIIB.txt --l1 1 --z ../newData/weightAll/BIIB.txt 2> /dev/null
creg -x ../newData/trainXall/PCG.json -y ../newData/trainYall/PCG.txt --l1 1 --z ../newData/weightAll/PCG.txt 2> /dev/null
creg -x ../newData/trainXall/POM.json -y ../newData/trainYall/POM.txt --l1 1 --z ../newData/weightAll/POM.txt 2> /dev/null
creg -x ../newData/trainXall/AKAM.json -y ../newData/trainYall/AKAM.txt --l1 1 --z ../newData/weightAll/AKAM.txt 2> /dev/null
creg -x ../newData/trainXall/DHI.json -y ../newData/trainYall/DHI.txt --l1 1 --z ../newData/weightAll/DHI.txt 2> /dev/null
creg -x ../newData/trainXall/M.json -y ../newData/trainYall/M.txt --l1 1 --z ../newData/weightAll/M.txt 2> /dev/null
creg -x ../newData/trainXall/INTU.json -y ../newData/trainYall/INTU.txt --l1 1 --z ../newData/weightAll/INTU.txt 2> /dev/null
creg -x ../newData/trainXall/SLM.json -y ../newData/trainYall/SLM.txt --l1 1 --z ../newData/weightAll/SLM.txt 2> /dev/null
creg -x ../newData/trainXall/ALXN.json -y ../newData/trainYall/ALXN.txt --l1 1 --z ../newData/weightAll/ALXN.txt 2> /dev/null
creg -x ../newData/trainXall/DHR.json -y ../newData/trainYall/DHR.txt --l1 1 --z ../newData/weightAll/DHR.txt 2> /dev/null
creg -x ../newData/trainXall/SLB.json -y ../newData/trainYall/SLB.txt --l1 1 --z ../newData/weightAll/SLB.txt 2> /dev/null
creg -x ../newData/trainXall/MCO.json -y ../newData/trainYall/MCO.txt --l1 1 --z ../newData/weightAll/MCO.txt 2> /dev/null
creg -x ../newData/trainXall/MCK.json -y ../newData/trainYall/MCK.txt --l1 1 --z ../newData/weightAll/MCK.txt 2> /dev/null
creg -x ../newData/trainXall/MCD.json -y ../newData/trainYall/MCD.txt --l1 1 --z ../newData/weightAll/MCD.txt 2> /dev/null
creg -x ../newData/trainXall/NRG.json -y ../newData/trainYall/NRG.txt --l1 1 --z ../newData/weightAll/NRG.txt 2> /dev/null
creg -x ../newData/trainXall/PBCT.json -y ../newData/trainYall/PBCT.txt --l1 1 --z ../newData/weightAll/PBCT.txt 2> /dev/null
creg -x ../newData/trainXall/VTR.json -y ../newData/trainYall/VTR.txt --l1 1 --z ../newData/weightAll/VTR.txt 2> /dev/null
creg -x ../newData/trainXall/AXP.json -y ../newData/trainYall/AXP.txt --l1 1 --z ../newData/weightAll/AXP.txt 2> /dev/null
creg -x ../newData/trainXall/NFLX.json -y ../newData/trainYall/NFLX.txt --l1 1 --z ../newData/weightAll/NFLX.txt 2> /dev/null
creg -x ../newData/trainXall/EXC.json -y ../newData/trainYall/EXC.txt --l1 1 --z ../newData/weightAll/EXC.txt 2> /dev/null
creg -x ../newData/trainXall/AAPL.json -y ../newData/trainYall/AAPL.txt --l1 1 --z ../newData/weightAll/AAPL.txt 2> /dev/null
creg -x ../newData/trainXall/SJM.json -y ../newData/trainYall/SJM.txt --l1 1 --z ../newData/weightAll/SJM.txt 2> /dev/null
creg -x ../newData/trainXall/SRCL.json -y ../newData/trainYall/SRCL.txt --l1 1 --z ../newData/weightAll/SRCL.txt 2> /dev/null
creg -x ../newData/trainXall/WU.json -y ../newData/trainYall/WU.txt --l1 1 --z ../newData/weightAll/WU.txt 2> /dev/null
creg -x ../newData/trainXall/WY.json -y ../newData/trainYall/WY.txt --l1 1 --z ../newData/weightAll/WY.txt 2> /dev/null
creg -x ../newData/trainXall/VNO.json -y ../newData/trainYall/VNO.txt --l1 1 --z ../newData/weightAll/VNO.txt 2> /dev/null
creg -x ../newData/trainXall/HSP.json -y ../newData/trainYall/HSP.txt --l1 1 --z ../newData/weightAll/HSP.txt 2> /dev/null
creg -x ../newData/trainXall/HST.json -y ../newData/trainYall/HST.txt --l1 1 --z ../newData/weightAll/HST.txt 2> /dev/null
creg -x ../newData/trainXall/HSY.json -y ../newData/trainYall/HSY.txt --l1 1 --z ../newData/weightAll/HSY.txt 2> /dev/null
creg -x ../newData/trainXall/CTSH.json -y ../newData/trainYall/CTSH.txt --l1 1 --z ../newData/weightAll/CTSH.txt 2> /dev/null
creg -x ../newData/trainXall/HAL.json -y ../newData/trainYall/HAL.txt --l1 1 --z ../newData/weightAll/HAL.txt 2> /dev/null
creg -x ../newData/trainXall/FITB.json -y ../newData/trainYall/FITB.txt --l1 1 --z ../newData/weightAll/FITB.txt 2> /dev/null
creg -x ../newData/trainXall/EQR.json -y ../newData/trainYall/EQR.txt --l1 1 --z ../newData/weightAll/EQR.txt 2> /dev/null
creg -x ../newData/trainXall/EQT.json -y ../newData/trainYall/EQT.txt --l1 1 --z ../newData/weightAll/EQT.txt 2> /dev/null
creg -x ../newData/trainXall/GPC.json -y ../newData/trainYall/GPC.txt --l1 1 --z ../newData/weightAll/GPC.txt 2> /dev/null
creg -x ../newData/trainXall/PDCO.json -y ../newData/trainYall/PDCO.txt --l1 1 --z ../newData/weightAll/PDCO.txt 2> /dev/null
creg -x ../newData/trainXall/X.json -y ../newData/trainYall/X.txt --l1 1 --z ../newData/weightAll/X.txt 2> /dev/null
creg -x ../newData/trainXall/HAR.json -y ../newData/trainYall/HAR.txt --l1 1 --z ../newData/weightAll/HAR.txt 2> /dev/null
creg -x ../newData/trainXall/HAS.json -y ../newData/trainYall/HAS.txt --l1 1 --z ../newData/weightAll/HAS.txt 2> /dev/null
creg -x ../newData/trainXall/THC.json -y ../newData/trainYall/THC.txt --l1 1 --z ../newData/weightAll/THC.txt 2> /dev/null
creg -x ../newData/trainXall/PH.json -y ../newData/trainYall/PH.txt --l1 1 --z ../newData/weightAll/PH.txt 2> /dev/null
creg -x ../newData/trainXall/GPS.json -y ../newData/trainYall/GPS.txt --l1 1 --z ../newData/weightAll/GPS.txt 2> /dev/null
creg -x ../newData/trainXall/PHM.json -y ../newData/trainYall/PHM.txt --l1 1 --z ../newData/weightAll/PHM.txt 2> /dev/null
creg -x ../newData/trainXall/SYK.json -y ../newData/trainYall/SYK.txt --l1 1 --z ../newData/weightAll/SYK.txt 2> /dev/null
creg -x ../newData/trainXall/BRCM.json -y ../newData/trainYall/BRCM.txt --l1 1 --z ../newData/weightAll/BRCM.txt 2> /dev/null
creg -x ../newData/trainXall/SYY.json -y ../newData/trainYall/SYY.txt --l1 1 --z ../newData/weightAll/SYY.txt 2> /dev/null
creg -x ../newData/trainXall/AEP.json -y ../newData/trainYall/AEP.txt --l1 1 --z ../newData/weightAll/AEP.txt 2> /dev/null
creg -x ../newData/trainXall/AES.json -y ../newData/trainYall/AES.txt --l1 1 --z ../newData/weightAll/AES.txt 2> /dev/null
creg -x ../newData/trainXall/AET.json -y ../newData/trainYall/AET.txt --l1 1 --z ../newData/weightAll/AET.txt 2> /dev/null
creg -x ../newData/trainXall/EMC.json -y ../newData/trainYall/EMC.txt --l1 1 --z ../newData/weightAll/EMC.txt 2> /dev/null
creg -x ../newData/trainXall/EMN.json -y ../newData/trainYall/EMN.txt --l1 1 --z ../newData/weightAll/EMN.txt 2> /dev/null
creg -x ../newData/trainXall/GRMN.json -y ../newData/trainYall/GRMN.txt --l1 1 --z ../newData/weightAll/GRMN.txt 2> /dev/null
creg -x ../newData/trainXall/ESRX.json -y ../newData/trainYall/ESRX.txt --l1 1 --z ../newData/weightAll/ESRX.txt 2> /dev/null
creg -x ../newData/trainXall/AMAT.json -y ../newData/trainYall/AMAT.txt --l1 1 --z ../newData/weightAll/AMAT.txt 2> /dev/null
creg -x ../newData/trainXall/FTR.json -y ../newData/trainYall/FTR.txt --l1 1 --z ../newData/weightAll/FTR.txt 2> /dev/null
creg -x ../newData/trainXall/AEE.json -y ../newData/trainYall/AEE.txt --l1 1 --z ../newData/weightAll/AEE.txt 2> /dev/null
creg -x ../newData/trainXall/CTAS.json -y ../newData/trainYall/CTAS.txt --l1 1 --z ../newData/weightAll/CTAS.txt 2> /dev/null
creg -x ../newData/trainXall/EMR.json -y ../newData/trainYall/EMR.txt --l1 1 --z ../newData/weightAll/EMR.txt 2> /dev/null
creg -x ../newData/trainXall/FDX.json -y ../newData/trainYall/FDX.txt --l1 1 --z ../newData/weightAll/FDX.txt 2> /dev/null
creg -x ../newData/trainXall/CRM.json -y ../newData/trainYall/CRM.txt --l1 1 --z ../newData/weightAll/CRM.txt 2> /dev/null
creg -x ../newData/trainXall/NWSA.json -y ../newData/trainYall/NWSA.txt --l1 1 --z ../newData/weightAll/NWSA.txt 2> /dev/null
creg -x ../newData/trainXall/PX.json -y ../newData/trainYall/PX.txt --l1 1 --z ../newData/weightAll/PX.txt 2> /dev/null
creg -x ../newData/trainXall/PG.json -y ../newData/trainYall/PG.txt --l1 1 --z ../newData/weightAll/PG.txt 2> /dev/null
creg -x ../newData/trainXall/CTXS.json -y ../newData/trainYall/CTXS.txt --l1 1 --z ../newData/weightAll/CTXS.txt 2> /dev/null
creg -x ../newData/trainXall/PM.json -y ../newData/trainYall/PM.txt --l1 1 --z ../newData/weightAll/PM.txt 2> /dev/null
creg -x ../newData/trainXall/EFX.json -y ../newData/trainYall/EFX.txt --l1 1 --z ../newData/weightAll/EFX.txt 2> /dev/null
creg -x ../newData/trainXall/C.json -y ../newData/trainYall/C.txt --l1 1 --z ../newData/weightAll/C.txt 2> /dev/null
creg -x ../newData/trainXall/S.json -y ../newData/trainYall/S.txt --l1 1 --z ../newData/weightAll/S.txt 2> /dev/null
creg -x ../newData/trainXall/QCOM.json -y ../newData/trainYall/QCOM.txt --l1 1 --z ../newData/weightAll/QCOM.txt 2> /dev/null
creg -x ../newData/trainXall/XRX.json -y ../newData/trainYall/XRX.txt --l1 1 --z ../newData/weightAll/XRX.txt 2> /dev/null
creg -x ../newData/trainXall/ANF.json -y ../newData/trainYall/ANF.txt --l1 1 --z ../newData/weightAll/ANF.txt 2> /dev/null
creg -x ../newData/trainXall/MOS.json -y ../newData/trainYall/MOS.txt --l1 1 --z ../newData/weightAll/MOS.txt 2> /dev/null
creg -x ../newData/trainXall/PSA.json -y ../newData/trainYall/PSA.txt --l1 1 --z ../newData/weightAll/PSA.txt 2> /dev/null
creg -x ../newData/trainXall/MON.json -y ../newData/trainYall/MON.txt --l1 1 --z ../newData/weightAll/MON.txt 2> /dev/null
creg -x ../newData/trainXall/JOY.json -y ../newData/trainYall/JOY.txt --l1 1 --z ../newData/weightAll/JOY.txt 2> /dev/null
creg -x ../newData/trainXall/MCHP.json -y ../newData/trainYall/MCHP.txt --l1 1 --z ../newData/weightAll/MCHP.txt 2> /dev/null
creg -x ../newData/trainXall/ALTR.json -y ../newData/trainYall/ALTR.txt --l1 1 --z ../newData/weightAll/ALTR.txt 2> /dev/null
creg -x ../newData/trainXall/ETR.json -y ../newData/trainYall/ETR.txt --l1 1 --z ../newData/weightAll/ETR.txt 2> /dev/null
creg -x ../newData/trainXall/COP.json -y ../newData/trainYall/COP.txt --l1 1 --z ../newData/weightAll/COP.txt 2> /dev/null
creg -x ../newData/trainXall/HES.json -y ../newData/trainYall/HES.txt --l1 1 --z ../newData/weightAll/HES.txt 2> /dev/null
creg -x ../newData/trainXall/DVN.json -y ../newData/trainYall/DVN.txt --l1 1 --z ../newData/weightAll/DVN.txt 2> /dev/null
creg -x ../newData/trainXall/KMB.json -y ../newData/trainYall/KMB.txt --l1 1 --z ../newData/weightAll/KMB.txt 2> /dev/null
creg -x ../newData/trainXall/COV.json -y ../newData/trainYall/COV.txt --l1 1 --z ../newData/weightAll/COV.txt 2> /dev/null
creg -x ../newData/trainXall/DVA.json -y ../newData/trainYall/DVA.txt --l1 1 --z ../newData/weightAll/DVA.txt 2> /dev/null
creg -x ../newData/trainXall/GWW.json -y ../newData/trainYall/GWW.txt --l1 1 --z ../newData/weightAll/GWW.txt 2> /dev/null
creg -x ../newData/trainXall/FISV.json -y ../newData/trainYall/FISV.txt --l1 1 --z ../newData/weightAll/FISV.txt 2> /dev/null
creg -x ../newData/trainXall/COG.json -y ../newData/trainYall/COG.txt --l1 1 --z ../newData/weightAll/COG.txt 2> /dev/null
creg -x ../newData/trainXall/COF.json -y ../newData/trainYall/COF.txt --l1 1 --z ../newData/weightAll/COF.txt 2> /dev/null
creg -x ../newData/trainXall/COH.json -y ../newData/trainYall/COH.txt --l1 1 --z ../newData/weightAll/COH.txt 2> /dev/null
creg -x ../newData/trainXall/TMK.json -y ../newData/trainYall/TMK.txt --l1 1 --z ../newData/weightAll/TMK.txt 2> /dev/null
creg -x ../newData/trainXall/ETN.json -y ../newData/trainYall/ETN.txt --l1 1 --z ../newData/weightAll/ETN.txt 2> /dev/null
creg -x ../newData/trainXall/COL.json -y ../newData/trainYall/COL.txt --l1 1 --z ../newData/weightAll/COL.txt 2> /dev/null
creg -x ../newData/trainXall/BCR.json -y ../newData/trainYall/BCR.txt --l1 1 --z ../newData/weightAll/BCR.txt 2> /dev/null
creg -x ../newData/trainXall/KMX.json -y ../newData/trainYall/KMX.txt --l1 1 --z ../newData/weightAll/KMX.txt 2> /dev/null
creg -x ../newData/trainXall/DLTR.json -y ../newData/trainYall/DLTR.txt --l1 1 --z ../newData/weightAll/DLTR.txt 2> /dev/null
creg -x ../newData/trainXall/CI.json -y ../newData/trainYall/CI.txt --l1 1 --z ../newData/weightAll/CI.txt 2> /dev/null
creg -x ../newData/trainXall/JDSU.json -y ../newData/trainYall/JDSU.txt --l1 1 --z ../newData/weightAll/JDSU.txt 2> /dev/null
creg -x ../newData/trainXall/CL.json -y ../newData/trainYall/CL.txt --l1 1 --z ../newData/weightAll/CL.txt 2> /dev/null
creg -x ../newData/trainXall/WAG.json -y ../newData/trainYall/WAG.txt --l1 1 --z ../newData/weightAll/WAG.txt 2> /dev/null
creg -x ../newData/trainXall/CB.json -y ../newData/trainYall/CB.txt --l1 1 --z ../newData/weightAll/CB.txt 2> /dev/null
creg -x ../newData/trainXall/CA.json -y ../newData/trainYall/CA.txt --l1 1 --z ../newData/weightAll/CA.txt 2> /dev/null
creg -x ../newData/trainXall/CF.json -y ../newData/trainYall/CF.txt --l1 1 --z ../newData/weightAll/CF.txt 2> /dev/null
creg -x ../newData/trainXall/WAT.json -y ../newData/trainYall/WAT.txt --l1 1 --z ../newData/weightAll/WAT.txt 2> /dev/null
creg -x ../newData/trainXall/CHRW.json -y ../newData/trainYall/CHRW.txt --l1 1 --z ../newData/weightAll/CHRW.txt 2> /dev/null
creg -x ../newData/trainXall/TDC.json -y ../newData/trainYall/TDC.txt --l1 1 --z ../newData/weightAll/TDC.txt 2> /dev/null
creg -x ../newData/trainXall/SBUX.json -y ../newData/trainYall/SBUX.txt --l1 1 --z ../newData/weightAll/SBUX.txt 2> /dev/null
creg -x ../newData/trainXall/PLD.json -y ../newData/trainYall/PLD.txt --l1 1 --z ../newData/weightAll/PLD.txt 2> /dev/null
creg -x ../newData/trainXall/HCBK.json -y ../newData/trainYall/HCBK.txt --l1 1 --z ../newData/weightAll/HCBK.txt 2> /dev/null
creg -x ../newData/trainXall/PLL.json -y ../newData/trainYall/PLL.txt --l1 1 --z ../newData/weightAll/PLL.txt 2> /dev/null
creg -x ../newData/trainXall/CMCSA.json -y ../newData/trainYall/CMCSA.txt --l1 1 --z ../newData/weightAll/CMCSA.txt 2> /dev/null
creg -x ../newData/trainXall/FHN.json -y ../newData/trainYall/FHN.txt --l1 1 --z ../newData/weightAll/FHN.txt 2> /dev/null
creg -x ../newData/trainXall/MKC.json -y ../newData/trainYall/MKC.txt --l1 1 --z ../newData/weightAll/MKC.txt 2> /dev/null
creg -x ../newData/trainXall/GNW.json -y ../newData/trainYall/GNW.txt --l1 1 --z ../newData/weightAll/GNW.txt 2> /dev/null
creg -x ../newData/trainXall/CVX.json -y ../newData/trainYall/CVX.txt --l1 1 --z ../newData/weightAll/CVX.txt 2> /dev/null
creg -x ../newData/trainXall/AIZ.json -y ../newData/trainYall/AIZ.txt --l1 1 --z ../newData/weightAll/AIZ.txt 2> /dev/null
creg -x ../newData/trainXall/EIX.json -y ../newData/trainYall/EIX.txt --l1 1 --z ../newData/weightAll/EIX.txt 2> /dev/null
creg -x ../newData/trainXall/AIV.json -y ../newData/trainYall/AIV.txt --l1 1 --z ../newData/weightAll/AIV.txt 2> /dev/null
creg -x ../newData/trainXall/CVS.json -y ../newData/trainYall/CVS.txt --l1 1 --z ../newData/weightAll/CVS.txt 2> /dev/null
creg -x ../newData/trainXall/LOW.json -y ../newData/trainYall/LOW.txt --l1 1 --z ../newData/weightAll/LOW.txt 2> /dev/null
creg -x ../newData/trainXall/TXT.json -y ../newData/trainYall/TXT.txt --l1 1 --z ../newData/weightAll/TXT.txt 2> /dev/null
creg -x ../newData/trainXall/AIG.json -y ../newData/trainYall/AIG.txt --l1 1 --z ../newData/weightAll/AIG.txt 2> /dev/null
creg -x ../newData/trainXall/CVC.json -y ../newData/trainYall/CVC.txt --l1 1 --z ../newData/weightAll/CVC.txt 2> /dev/null
creg -x ../newData/trainXall/DIS.json -y ../newData/trainYall/DIS.txt --l1 1 --z ../newData/weightAll/DIS.txt 2> /dev/null
creg -x ../newData/trainXall/PPG.json -y ../newData/trainYall/PPG.txt --l1 1 --z ../newData/weightAll/PPG.txt 2> /dev/null
creg -x ../newData/trainXall/MNST.json -y ../newData/trainYall/MNST.txt --l1 1 --z ../newData/weightAll/MNST.txt 2> /dev/null
creg -x ../newData/trainXall/NSC.json -y ../newData/trainYall/NSC.txt --l1 1 --z ../newData/weightAll/NSC.txt 2> /dev/null
creg -x ../newData/trainXall/GAS.json -y ../newData/trainYall/GAS.txt --l1 1 --z ../newData/weightAll/GAS.txt 2> /dev/null
creg -x ../newData/trainXall/PPL.json -y ../newData/trainYall/PPL.txt --l1 1 --z ../newData/weightAll/PPL.txt 2> /dev/null
creg -x ../newData/trainXall/OKE.json -y ../newData/trainYall/OKE.txt --l1 1 --z ../newData/weightAll/OKE.txt 2> /dev/null
creg -x ../newData/trainXall/GOOG.json -y ../newData/trainYall/GOOG.txt --l1 1 --z ../newData/weightAll/GOOG.txt 2> /dev/null
creg -x ../newData/trainXall/JCP.json -y ../newData/trainYall/JCP.txt --l1 1 --z ../newData/weightAll/JCP.txt 2> /dev/null
creg -x ../newData/trainXall/IP.json -y ../newData/trainYall/IP.txt --l1 1 --z ../newData/weightAll/IP.txt 2> /dev/null
creg -x ../newData/trainXall/HPQ.json -y ../newData/trainYall/HPQ.txt --l1 1 --z ../newData/weightAll/HPQ.txt 2> /dev/null
creg -x ../newData/trainXall/IR.json -y ../newData/trainYall/IR.txt --l1 1 --z ../newData/weightAll/IR.txt 2> /dev/null
creg -x ../newData/trainXall/IRM.json -y ../newData/trainYall/IRM.txt --l1 1 --z ../newData/weightAll/IRM.txt 2> /dev/null
creg -x ../newData/trainXall/MTB.json -y ../newData/trainYall/MTB.txt --l1 1 --z ../newData/weightAll/MTB.txt 2> /dev/null
creg -x ../newData/trainXall/UTX.json -y ../newData/trainYall/UTX.txt --l1 1 --z ../newData/weightAll/UTX.txt 2> /dev/null
creg -x ../newData/trainXall/JCI.json -y ../newData/trainYall/JCI.txt --l1 1 --z ../newData/weightAll/JCI.txt 2> /dev/null
creg -x ../newData/trainXall/PWR.json -y ../newData/trainYall/PWR.txt --l1 1 --z ../newData/weightAll/PWR.txt 2> /dev/null
creg -x ../newData/trainXall/CSCO.json -y ../newData/trainYall/CSCO.txt --l1 1 --z ../newData/weightAll/CSCO.txt 2> /dev/null
creg -x ../newData/trainXall/ARG.json -y ../newData/trainYall/ARG.txt --l1 1 --z ../newData/weightAll/ARG.txt 2> /dev/null
creg -x ../newData/trainXall/WDC.json -y ../newData/trainYall/WDC.txt --l1 1 --z ../newData/weightAll/WDC.txt 2> /dev/null
creg -x ../newData/trainXall/BA.json -y ../newData/trainYall/BA.txt --l1 1 --z ../newData/weightAll/BA.txt 2> /dev/null
creg -x ../newData/trainXall/BK.json -y ../newData/trainYall/BK.txt --l1 1 --z ../newData/weightAll/BK.txt 2> /dev/null
creg -x ../newData/trainXall/DRI.json -y ../newData/trainYall/DRI.txt --l1 1 --z ../newData/weightAll/DRI.txt 2> /dev/null
creg -x ../newData/trainXall/CCL.json -y ../newData/trainYall/CCL.txt --l1 1 --z ../newData/weightAll/CCL.txt 2> /dev/null
creg -x ../newData/trainXall/CCI.json -y ../newData/trainYall/CCI.txt --l1 1 --z ../newData/weightAll/CCI.txt 2> /dev/null
creg -x ../newData/trainXall/CCE.json -y ../newData/trainYall/CCE.txt --l1 1 --z ../newData/weightAll/CCE.txt 2> /dev/null
creg -x ../newData/trainXall/TIF.json -y ../newData/trainYall/TIF.txt --l1 1 --z ../newData/weightAll/TIF.txt 2> /dev/null
creg -x ../newData/trainXall/FLIR.json -y ../newData/trainYall/FLIR.txt --l1 1 --z ../newData/weightAll/FLIR.txt 2> /dev/null
creg -x ../newData/trainXall/SYMC.json -y ../newData/trainYall/SYMC.txt --l1 1 --z ../newData/weightAll/SYMC.txt 2> /dev/null
creg -x ../newData/trainXall/MYL.json -y ../newData/trainYall/MYL.txt --l1 1 --z ../newData/weightAll/MYL.txt 2> /dev/null
creg -x ../newData/trainXall/SIAL.json -y ../newData/trainYall/SIAL.txt --l1 1 --z ../newData/weightAll/SIAL.txt 2> /dev/null
creg -x ../newData/trainXall/D.json -y ../newData/trainYall/D.txt --l1 1 --z ../newData/weightAll/D.txt 2> /dev/null
creg -x ../newData/trainXall/PEP.json -y ../newData/trainYall/PEP.txt --l1 1 --z ../newData/weightAll/PEP.txt 2> /dev/null
creg -x ../newData/trainXall/WMT.json -y ../newData/trainYall/WMT.txt --l1 1 --z ../newData/weightAll/WMT.txt 2> /dev/null
creg -x ../newData/trainXall/VZ.json -y ../newData/trainYall/VZ.txt --l1 1 --z ../newData/weightAll/VZ.txt 2> /dev/null
creg -x ../newData/trainXall/T.json -y ../newData/trainYall/T.txt --l1 1 --z ../newData/weightAll/T.txt 2> /dev/null
creg -x ../newData/trainXall/WMB.json -y ../newData/trainYall/WMB.txt --l1 1 --z ../newData/weightAll/WMB.txt 2> /dev/null
creg -x ../newData/trainXall/VRSN.json -y ../newData/trainYall/VRSN.txt --l1 1 --z ../newData/weightAll/VRSN.txt 2> /dev/null
creg -x ../newData/trainXall/OI.json -y ../newData/trainYall/OI.txt --l1 1 --z ../newData/weightAll/OI.txt 2> /dev/null
creg -x ../newData/trainXall/CINF.json -y ../newData/trainYall/CINF.txt --l1 1 --z ../newData/weightAll/CINF.txt 2> /dev/null
creg -x ../newData/trainXall/NTRS.json -y ../newData/trainYall/NTRS.txt --l1 1 --z ../newData/weightAll/NTRS.txt 2> /dev/null
creg -x ../newData/trainXall/MWV.json -y ../newData/trainYall/MWV.txt --l1 1 --z ../newData/weightAll/MWV.txt 2> /dev/null
creg -x ../newData/trainXall/ESV.json -y ../newData/trainYall/ESV.txt --l1 1 --z ../newData/weightAll/ESV.txt 2> /dev/null
creg -x ../newData/trainXall/HP.json -y ../newData/trainYall/HP.txt --l1 1 --z ../newData/weightAll/HP.txt 2> /dev/null
creg -x ../newData/trainXall/FLR.json -y ../newData/trainYall/FLR.txt --l1 1 --z ../newData/weightAll/FLR.txt 2> /dev/null
creg -x ../newData/trainXall/HD.json -y ../newData/trainYall/HD.txt --l1 1 --z ../newData/weightAll/HD.txt 2> /dev/null
creg -x ../newData/trainXall/LLY.json -y ../newData/trainYall/LLY.txt --l1 1 --z ../newData/weightAll/LLY.txt 2> /dev/null
creg -x ../newData/trainXall/PEG.json -y ../newData/trainYall/PEG.txt --l1 1 --z ../newData/weightAll/PEG.txt 2> /dev/null
creg -x ../newData/trainXall/INTC.json -y ../newData/trainYall/INTC.txt --l1 1 --z ../newData/weightAll/INTC.txt 2> /dev/null
creg -x ../newData/trainXall/SCG.json -y ../newData/trainYall/SCG.txt --l1 1 --z ../newData/weightAll/SCG.txt 2> /dev/null
creg -x ../newData/trainXall/AMD.json -y ../newData/trainYall/AMD.txt --l1 1 --z ../newData/weightAll/AMD.txt 2> /dev/null
creg -x ../newData/trainXall/LLL.json -y ../newData/trainYall/LLL.txt --l1 1 --z ../newData/weightAll/LLL.txt 2> /dev/null
creg -x ../newData/trainXall/NWL.json -y ../newData/trainYall/NWL.txt --l1 1 --z ../newData/weightAll/NWL.txt 2> /dev/null
creg -x ../newData/trainXall/AMP.json -y ../newData/trainYall/AMP.txt --l1 1 --z ../newData/weightAll/AMP.txt 2> /dev/null
creg -x ../newData/trainXall/TMO.json -y ../newData/trainYall/TMO.txt --l1 1 --z ../newData/weightAll/TMO.txt 2> /dev/null
creg -x ../newData/trainXall/AMT.json -y ../newData/trainYall/AMT.txt --l1 1 --z ../newData/weightAll/AMT.txt 2> /dev/null
creg -x ../newData/trainXall/LRCX.json -y ../newData/trainYall/LRCX.txt --l1 1 --z ../newData/weightAll/LRCX.txt 2> /dev/null
creg -x ../newData/trainXall/CNX.json -y ../newData/trainYall/CNX.txt --l1 1 --z ../newData/weightAll/CNX.txt 2> /dev/null
creg -x ../newData/trainXall/YHOO.json -y ../newData/trainYall/YHOO.txt --l1 1 --z ../newData/weightAll/YHOO.txt 2> /dev/null
creg -x ../newData/trainXall/PBI.json -y ../newData/trainYall/PBI.txt --l1 1 --z ../newData/weightAll/PBI.txt 2> /dev/null
creg -x ../newData/trainXall/BDX.json -y ../newData/trainYall/BDX.txt --l1 1 --z ../newData/weightAll/BDX.txt 2> /dev/null
creg -x ../newData/trainXall/TRV.json -y ../newData/trainYall/TRV.txt --l1 1 --z ../newData/weightAll/TRV.txt 2> /dev/null
creg -x ../newData/trainXall/AVY.json -y ../newData/trainYall/AVY.txt --l1 1 --z ../newData/weightAll/AVY.txt 2> /dev/null
creg -x ../newData/trainXall/AVP.json -y ../newData/trainYall/AVP.txt --l1 1 --z ../newData/weightAll/AVP.txt 2> /dev/null
creg -x ../newData/trainXall/MDLZ.json -y ../newData/trainYall/MDLZ.txt --l1 1 --z ../newData/weightAll/MDLZ.txt 2> /dev/null
creg -x ../newData/trainXall/AVB.json -y ../newData/trainYall/AVB.txt --l1 1 --z ../newData/weightAll/AVB.txt 2> /dev/null
creg -x ../newData/trainXall/NEM.json -y ../newData/trainYall/NEM.txt --l1 1 --z ../newData/weightAll/NEM.txt 2> /dev/null
creg -x ../newData/trainXall/FOSL.json -y ../newData/trainYall/FOSL.txt --l1 1 --z ../newData/weightAll/FOSL.txt 2> /dev/null
creg -x ../newData/trainXall/ACE.json -y ../newData/trainYall/ACE.txt --l1 1 --z ../newData/weightAll/ACE.txt 2> /dev/null
creg -x ../newData/trainXall/NEE.json -y ../newData/trainYall/NEE.txt --l1 1 --z ../newData/weightAll/NEE.txt 2> /dev/null
creg -x ../newData/trainXall/ACN.json -y ../newData/trainYall/ACN.txt --l1 1 --z ../newData/weightAll/ACN.txt 2> /dev/null
creg -x ../newData/trainXall/NI.json -y ../newData/trainYall/NI.txt --l1 1 --z ../newData/weightAll/NI.txt 2> /dev/null
creg -x ../newData/trainXall/TEL.json -y ../newData/trainYall/TEL.txt --l1 1 --z ../newData/weightAll/TEL.txt 2> /dev/null
creg -x ../newData/trainXall/NBR.json -y ../newData/trainYall/NBR.txt --l1 1 --z ../newData/weightAll/NBR.txt 2> /dev/null
creg -x ../newData/trainXall/RRC.json -y ../newData/trainYall/RRC.txt --l1 1 --z ../newData/weightAll/RRC.txt 2> /dev/null
creg -x ../newData/trainXall/NE.json -y ../newData/trainYall/NE.txt --l1 1 --z ../newData/weightAll/NE.txt 2> /dev/null
creg -x ../newData/trainXall/FAST.json -y ../newData/trainYall/FAST.txt --l1 1 --z ../newData/weightAll/FAST.txt 2> /dev/null
creg -x ../newData/trainXall/TEG.json -y ../newData/trainYall/TEG.txt --l1 1 --z ../newData/weightAll/TEG.txt 2> /dev/null
creg -x ../newData/trainXall/NBL.json -y ../newData/trainYall/NBL.txt --l1 1 --z ../newData/weightAll/NBL.txt 2> /dev/null
creg -x ../newData/trainXall/TER.json -y ../newData/trainYall/TER.txt --l1 1 --z ../newData/weightAll/TER.txt 2> /dev/null
creg -x ../newData/trainXall/FLS.json -y ../newData/trainYall/FLS.txt --l1 1 --z ../newData/weightAll/FLS.txt 2> /dev/null
creg -x ../newData/trainXall/LLTC.json -y ../newData/trainYall/LLTC.txt --l1 1 --z ../newData/weightAll/LLTC.txt 2> /dev/null
creg -x ../newData/trainXall/ADP.json -y ../newData/trainYall/ADP.txt --l1 1 --z ../newData/weightAll/ADP.txt 2> /dev/null
creg -x ../newData/trainXall/DNB.json -y ../newData/trainYall/DNB.txt --l1 1 --z ../newData/weightAll/DNB.txt 2> /dev/null
creg -x ../newData/trainXall/GILD.json -y ../newData/trainYall/GILD.txt --l1 1 --z ../newData/weightAll/GILD.txt 2> /dev/null
creg -x ../newData/trainXall/GME.json -y ../newData/trainYall/GME.txt --l1 1 --z ../newData/weightAll/GME.txt 2> /dev/null
creg -x ../newData/trainXall/RDC.json -y ../newData/trainYall/RDC.txt --l1 1 --z ../newData/weightAll/RDC.txt 2> /dev/null
creg -x ../newData/trainXall/DNR.json -y ../newData/trainYall/DNR.txt --l1 1 --z ../newData/weightAll/DNR.txt 2> /dev/null
creg -x ../newData/trainXall/JPM.json -y ../newData/trainYall/JPM.txt --l1 1 --z ../newData/weightAll/JPM.txt 2> /dev/null
creg -x ../newData/trainXall/ADM.json -y ../newData/trainYall/ADM.txt --l1 1 --z ../newData/weightAll/ADM.txt 2> /dev/null
creg -x ../newData/trainXall/ADI.json -y ../newData/trainYall/ADI.txt --l1 1 --z ../newData/weightAll/ADI.txt 2> /dev/null
creg -x ../newData/trainXall/VIAB.json -y ../newData/trainYall/VIAB.txt --l1 1 --z ../newData/weightAll/VIAB.txt 2> /dev/null
creg -x ../newData/trainXall/LEG.json -y ../newData/trainYall/LEG.txt --l1 1 --z ../newData/weightAll/LEG.txt 2> /dev/null
creg -x ../newData/trainXall/XEL.json -y ../newData/trainYall/XEL.txt --l1 1 --z ../newData/weightAll/XEL.txt 2> /dev/null
creg -x ../newData/trainXall/WIN.json -y ../newData/trainYall/WIN.txt --l1 1 --z ../newData/weightAll/WIN.txt 2> /dev/null
creg -x ../newData/trainXall/LEN.json -y ../newData/trainYall/LEN.txt --l1 1 --z ../newData/weightAll/LEN.txt 2> /dev/null
creg -x ../newData/trainXall/EBAY.json -y ../newData/trainYall/EBAY.txt --l1 1 --z ../newData/weightAll/EBAY.txt 2> /dev/null
creg -x ../newData/trainXall/MET.json -y ../newData/trainYall/MET.txt --l1 1 --z ../newData/weightAll/MET.txt 2> /dev/null
creg -x ../newData/trainXall/TWC.json -y ../newData/trainYall/TWC.txt --l1 1 --z ../newData/weightAll/TWC.txt 2> /dev/null
creg -x ../newData/trainXall/USB.json -y ../newData/trainYall/USB.txt --l1 1 --z ../newData/weightAll/USB.txt 2> /dev/null
creg -x ../newData/trainXall/AZO.json -y ../newData/trainYall/AZO.txt --l1 1 --z ../newData/weightAll/AZO.txt 2> /dev/null
creg -x ../newData/trainXall/MSI.json -y ../newData/trainYall/MSI.txt --l1 1 --z ../newData/weightAll/MSI.txt 2> /dev/null
creg -x ../newData/trainXall/TWX.json -y ../newData/trainYall/TWX.txt --l1 1 --z ../newData/weightAll/TWX.txt 2> /dev/null
creg -x ../newData/trainXall/PCAR.json -y ../newData/trainYall/PCAR.txt --l1 1 --z ../newData/weightAll/PCAR.txt 2> /dev/null
creg -x ../newData/trainXall/TXN.json -y ../newData/trainYall/TXN.txt --l1 1 --z ../newData/weightAll/TXN.txt 2> /dev/null
creg -x ../newData/trainXall/PETM.json -y ../newData/trainYall/PETM.txt --l1 1 --z ../newData/weightAll/PETM.txt 2> /dev/null
creg -x ../newData/trainXall/SRE.json -y ../newData/trainYall/SRE.txt --l1 1 --z ../newData/weightAll/SRE.txt 2> /dev/null
creg -x ../newData/trainXall/ORCL.json -y ../newData/trainYall/ORCL.txt --l1 1 --z ../newData/weightAll/ORCL.txt 2> /dev/null
creg -x ../newData/trainXall/TE.json -y ../newData/trainYall/TE.txt --l1 1 --z ../newData/weightAll/TE.txt 2> /dev/null
creg -x ../newData/trainXall/PXD.json -y ../newData/trainYall/PXD.txt --l1 1 --z ../newData/weightAll/PXD.txt 2> /dev/null
creg -x ../newData/trainXall/AA.json -y ../newData/trainYall/AA.txt --l1 1 --z ../newData/weightAll/AA.txt 2> /dev/null
creg -x ../newData/trainXall/HOG.json -y ../newData/trainYall/HOG.txt --l1 1 --z ../newData/weightAll/HOG.txt 2> /dev/null
creg -x ../newData/trainXall/PKI.json -y ../newData/trainYall/PKI.txt --l1 1 --z ../newData/weightAll/PKI.txt 2> /dev/null
creg -x ../newData/trainXall/CNP.json -y ../newData/trainYall/CNP.txt --l1 1 --z ../newData/weightAll/CNP.txt 2> /dev/null
creg -x ../newData/trainXall/HON.json -y ../newData/trainYall/HON.txt --l1 1 --z ../newData/weightAll/HON.txt 2> /dev/null
creg -x ../newData/trainXall/ICE.json -y ../newData/trainYall/ICE.txt --l1 1 --z ../newData/weightAll/ICE.txt 2> /dev/null
creg -x ../newData/trainXall/AN.json -y ../newData/trainYall/AN.txt --l1 1 --z ../newData/weightAll/AN.txt 2> /dev/null
creg -x ../newData/trainXall/HOT.json -y ../newData/trainYall/HOT.txt --l1 1 --z ../newData/weightAll/HOT.txt 2> /dev/null
creg -x ../newData/trainXall/ROK.json -y ../newData/trainYall/ROK.txt --l1 1 --z ../newData/weightAll/ROK.txt 2> /dev/null
creg -x ../newData/trainXall/TROW.json -y ../newData/trainYall/TROW.txt --l1 1 --z ../newData/weightAll/TROW.txt 2> /dev/null
creg -x ../newData/trainXall/ISRG.json -y ../newData/trainYall/ISRG.txt --l1 1 --z ../newData/weightAll/ISRG.txt 2> /dev/null
creg -x ../newData/trainXall/PFE.json -y ../newData/trainYall/PFE.txt --l1 1 --z ../newData/weightAll/PFE.txt 2> /dev/null
creg -x ../newData/trainXall/NKE.json -y ../newData/trainYall/NKE.txt --l1 1 --z ../newData/weightAll/NKE.txt 2> /dev/null
creg -x ../newData/trainXall/PFG.json -y ../newData/trainYall/PFG.txt --l1 1 --z ../newData/weightAll/PFG.txt 2> /dev/null
creg -x ../newData/trainXall/TSS.json -y ../newData/trainYall/TSS.txt --l1 1 --z ../newData/weightAll/TSS.txt 2> /dev/null
